version: '1.0'
services:

  api:
    build: ./backend/ERP
    ports:
      - "5259:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:80
      - CONNECTION_STRING=Server=${DATABASE_SERVER};Database=${DATABASE_NAME};User Id=${DATABASE_USER};Password=${DATABASE_PASSWORD};

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${API_URL}
    environment:
      - VITE_API_BASE_URL=${API_URL}
    ports:
      - "5173:80"
    depends_on:
      - api
  